services:
  airflow-init:
    build: .
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_metadata:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    depends_on:
      - postgres_metadata
    networks:
      - airflow-network

  postgres_analytics:
    image: postgres:13
    environment:
      - POSTGRES_USER=analytics_user
      - POSTGRES_PASSWORD=analytics_password
      - POSTGRES_DB=flight_analytics
    ports:
      - "5434:5432"  # Mapped to 5434 on host to avoid conflict
    networks:
      - airflow-network

  mysql_staging:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=flight_staging
      - MYSQL_USER=staging_user
      - MYSQL_PASSWORD=staging_password
    ports:
      - "3308:3306" # Mapped to 3308 on host
    networks:
      - airflow-network
    command: --default-authentication-plugin=mysql_native_password

  airflow-webserver:
    build: .
    command: webserver
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_metadata:5432/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
    depends_on:
      postgres_metadata:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow-network

  airflow-scheduler:
    build: .
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_metadata:5432/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
    depends_on:
      postgres_metadata:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow-network

  postgres_metadata:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - airflow-network

networks:
  airflow-network:
    driver: bridge
